version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  build:
    executor: node/default
    working_directory: ~/aeropods
    steps:
      - checkout
      - run:
          name: Node.js Version
          command: node --version
      - run:
          name: Yarn Version
          command: yarn --version
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
          cache-version: v1
          app-dir: ~/aeropods
      - run:
          name: Build Package
          command: yarn run build
  test:
    executor: node/default
    working_directory: ~/aeropods
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
          cache-version: v1
          app-dir: ~/aeropods
      - run:
          name: Perform unit tests
          command: yarn run test:unit

workflows:
  version: 2
  development:
    jobs:
      - build
      - test
